services:
  - type: web
    name: crawler-bot-protection
    env: node
    buildCommand: npm install --no-audit --no-fund && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # HTTPS/SSL settings for proxy
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      # Redis configuration - you'll need to set these in Render dashboard
      # - key: REDIS_URL
      #   value: your_redis_url_here
      # - key: REDIS_HOST
      #   value: your_redis_host_here
      # - key: REDIS_PORT
      #   value: your_redis_port_here
      # Proxy target
      - key: PROXY_TARGET
        value: https://demo-real-estate-prv4.onrender.com/
      # Bot protection settings
      - key: BOT_SESSION_DURATION_SECONDS
        value: 300
      - key: BATCH_CHARGE_SIZE
        value: 1000
      - key: MINIMUM_CHARGE_AMOUNT
        value: 5
      # Skyfire API settings - set these in Render dashboard
      # - key: BACKEND_API_URL
      #   value: https://api.skyfire.com
      # - key: SELLER_SKYFIRE_API_KEY
      #   value: your_api_key_here
      # JWT settings - set these in Render dashboard
      # - key: OFFICIAL_SKYFIRE_JWT_ISSUER
      #   value: https://auth.skyfire.com
      # - key: OFFICIAL_SKYFIRE_AGENT_ID
      #   value: your_agent_id_here
      # - key: OFFICIAL_SKYFIRE_JWT_ALGORITHM
      #   value: RS256
      # - key: OFFICIAL_SKYFIRE_EXPECTED_SSI
      #   value: your_expected_ssi_here
